Adding TC for BackupLocationWithEncryptionKey
portworx/torpedo pull request #1007
Opened 2023-01-17 13:14 UTC by skonda-px

**What this PR does / why we need it**:
  Adding test case for BackupLocationWithEncryptionKey

**Which issue(s) this PR fixes** (optional)
Closes #PA-468

**Special notes for your reviewer**:

2023-01-17 18:07 UTC, lsrinivas-pure requested changes

2023-01-17 18:07 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +func generate_encryption_key() string {
use camelcase format all the method names and variable names

2023-01-17 18:07 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +	providers := getProviders()
move these callls inside It , so that these are call only when test is triggered

2023-01-17 18:07 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +		time.Sleep(time.Minute * 1)
can we check if cloud credential is created rather than having a sleep?

2023-01-17 18:07 UTC, lsrinivas-pure commented on tests/common.go
> +	//encryptionKey := "torpedo"
delete this line if not required

2023-01-18 04:25 UTC, kshithijiyer-px requested changes

2023-01-18 04:25 UTC, kshithijiyer-px commented on tests/backup/backup_test.go
> +		log.Infof("No pre-setup required for this testcase")
Do we really need to log this?

2023-01-18 04:25 UTC, kshithijiyer-px commented on tests/backup/backup_test.go
> +		log.InfoD("Creating bucket,backup location and cloud setting")
Nit: Bucket isn't created here we are reusing the bucket.

2023-01-18 04:25 UTC, kshithijiyer-px commented on tests/backup/backup_test.go
> +		log.Infof("Cleanup started")
Do you really need this log? Can we use something like cleaning up Backups and restores?

2023-01-18 04:25 UTC, kshithijiyer-px commented on tests/backup/backup_test.go
> +		log.Infof("Cleanup done")
Do we need this to log?

2023-01-19 04:37 UTC, kshithijiyer-px commented on tests/backup/backup_test.go
> +		CreateBackupLocation(providers[0], backupLocationName, BackupLocationUID, CredName, CloudCredUID, bucketName[0], orgID, encryptionKey)
Here `bucketName` parameter should be `bucketName := fmt.Sprintf("%s-%s", provider, bucket_name[0])` so You would want to add this line above.

2023-01-19 05:47 UTC, lsrinivas-pure reviewed
gave minor comments , rest LGTM

2023-01-19 05:47 UTC, lsrinivas-pure commented on tests/common.go
> -	encryptionKey := "torpedo"
remove the commented lines if not required

2023-01-19 05:47 UTC, lsrinivas-pure commented on tests/backup/backup_basic_test.go
> +	StartTorpedoTest("Cleanup buckets", "Removing buckets", nil, 0)
change the bucket_name to camelcase

2023-01-19 07:29 UTC, mkoppal-px commented
Please add the Aetos dashboard link for the run

2023-01-20 02:25 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +			clusterStatus, clusterUid = RegisterBackupCluster(orgID, "", "")
Add log.InfoD here so that from dashboard we know what steps are executed

2023-01-20 02:25 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +		Step("Taking backup of applications", func() {
same here

2023-01-20 02:25 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +				backupName := fmt.Sprintf("%s-%s", BackupNamePrefix, namespace)
same here

2023-01-20 04:48 UTC, lsrinivas-pure approved these changes
LGTM

2023-01-20 07:15 UTC, merged