Addressed PA-498:Create multiple user and group
portworx/torpedo pull request #1025
Opened 2023-01-21 08:42 UTC by apimpalgaonkar

What this PR does / why we need it:
Creates Multiple users and groups 

Which issue(s) this PR fixes (optional)
Closes #https://portworx.atlassian.net/browse/PA-498
Testrail - https://portworx.testrail.net/index.php?/cases/view/58032&group_by=cases:section_id&group_id=3897&group_order=asc&display_deleted_cases=0

2023-01-21 09:58 UTC, vpinisetti-px requested changes
Please add verification steps. Meaning verify users & groups are getting created or not by listing users & groups or any other mechanism such as logging into user etc..

2023-01-21 10:03 UTC, vpinisetti-px commented on tests/backup/backup_test.go
> +	numberOfUsers := 4
Better take large number of users & groups

2023-01-21 10:43 UTC, lsrinivas-pure requested changes

2023-01-21 10:43 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +	groups := make([]string, 0)
please add starttorpedotest and endtorpedotest functions

2023-01-21 11:15 UTC, mkoppal-px commented
Please attach the aetos dashboard link after a successful run of this test

2023-01-23 10:10 UTC, apimpalgaonkar commented
Created new PR

2023-01-23 10:10 UTC, closed without merging