Removed already deleted backups to prevent backup delete from failing
portworx/torpedo pull request #1080
Opened 2023-02-01 11:56 UTC by snigdha-px

**What this PR does / why we need it**:
1)Removed already deleted backups to prevent backup delete from failing
2)Added verifysafely instead of verifyfatal to prevent cleaning up in case some cleanup in between fails
**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

2023-02-04 08:56 UTC, lsrinivas-pure requested changes

2023-02-04 08:56 UTC, lsrinivas-pure commented on drivers/backup/auth.go
> +	response, err := processHTTPRequest(method, reqURL, headers, strings.NewReader(string(dataBytes)))
how are you handling failed responses?

2023-02-04 08:56 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
>  				backupUID, err := backupDriver.GetBackupUID(ctx, backupName, orgID)
add ginkgorecover here

2023-02-04 08:56 UTC, lsrinivas-pure commented on tests/backup/backup_test.go
> +				dash.VerifySafely(err, nil, fmt.Sprintf("Getting backup UID for backup %v", backupName))
same here

2023-02-06 04:28 UTC, snigdha-px commented on tests/backup/backup_test.go
> +				dash.VerifySafely(err, nil, fmt.Sprintf("Getting backup UID for backup %v", backupName))
done!!

2023-02-06 04:28 UTC, snigdha-px commented on tests/backup/backup_test.go
>  				backupUID, err := backupDriver.GetBackupUID(ctx, backupName, orgID)
done

2023-02-06 08:56 UTC, lsrinivas-pure approved these changes
LGTM

2023-02-06 09:53 UTC, mkoppal-px approved these changes
LGTM

2023-02-06 09:53 UTC, merged