Added testcase:ScaleDownPxBackupPodWhileBackupAndRestoreIsInProgress: Pa-738
portworx/torpedo pull request #1246
Opened 2023-03-23 10:30 UTC by snigdha-px

**What this PR does / why we need it**:
Added testcase:ScaleDownPxBackupPodWhileBackupAndRestoreIsInProgress
**Which issue(s) this PR fixes** (optional)
Closes #
https://portworx.atlassian.net/browse/PA-738
**Special notes for your reviewer**:

2023-03-24 05:41 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
>  		log.InfoD("Deleting the remaining backups in case of failure")
log.InfoD("Deleting the remaining backups in case of failure") might be unnecessary.

2023-03-24 05:42 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			_, err = task.DoRetryWithTimeout(mongoDBPodStatus, podStatusTimeOut, podStatusRetryTime)
Did we log this error?

2023-03-24 05:42 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			_, err = task.DoRetryWithTimeout(mongoDBPodStatus, podStatusTimeOut, podStatusRetryTime)
Did we log this error?

2023-03-24 05:43 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +	backupLocationMap := make(map[string]string)
If possible, please assign values to variables within the JustBeforeEach block.

2023-03-24 05:45 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			srcClusterStatus, srcClusterUid = Inst().Backup.RegisterBackupCluster(orgID, SourceClusterName, "")
Please keep an ready-to-merge PR #1230. There will be no Inst().Backup.RegisterBackupCluster.

2023-03-24 05:47 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			backupDeployment, err = apps.Instance().UpdateDeployment(backupDeployment)
How about renaming the variable backupDeployment here to updatedBackupDeployment?

2023-03-24 05:48 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			dash.VerifyFatal(*backupDeployment.Spec.Replicas == originalReplicaCount, true, "Verify px-backup deployment replica after scaling back to original")
How about dash.VerifyFatal(*backupDeployment.Spec.Replicas,  originalReplicaCount, "Verify px-backup deployment replica after scaling back to original")?

2023-03-24 05:51 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +				dash.VerifyFatal(err, nil, "Inspecting the restore success for - "+restoreName)
How about log.FailOnError(err, "Getting the status for restore- "+restoreName) similar to backupSuccessCheck?

2023-03-24 05:53 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
>  				_, err = task.DoRetryWithTimeout(backupJobCancelStatus, maxWaitPeriodForBackupJobCancellation*time.Minute, backupJobCancellationRetryTime*time.Second)
Did we log this error?

2023-03-27 08:38 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			backupDeployment, err = apps.Instance().UpdateDeployment(backupDeployment)
Done.

2023-03-27 08:38 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
>  		log.InfoD("Deleting the remaining backups in case of failure")
Thanks!

2023-03-27 09:06 UTC, lsrinivas-pure requested changes

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +					adminBackups, error1 := GetAllBackupsAdmin()
log err also

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +			log.FailOnError(err, fmt.Sprintf("Getting px-backup deployment replica in backup namespace %s", pxBackupNS))
move this error handling immediately after GetDeployment call

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +			backupDeployment, err = apps.Instance().GetDeployment(pxBackupDeployment, pxBackupNS)
handle err here

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +			log.FailOnError(err, fmt.Sprintf("Scaling down px-backup deployment replica to 0"))
handle the err first else it might lead to panic

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +			backupDeployment, err = apps.Instance().GetDeployment(pxBackupDeployment, pxBackupNS)
handle err here

2023-03-27 09:06 UTC, lsrinivas-pure commented on tests/backup/backup_resiliency_test.go
> +		backupDeployment, err = apps.Instance().GetDeployment(pxBackupDeployment, pxBackupNS)
handle err here

2023-03-27 11:27 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +			srcClusterStatus, srcClusterUid = Inst().Backup.RegisterBackupCluster(orgID, SourceClusterName, "")
Thanks!

2023-03-27 13:26 UTC, KrishnaPhalgun28 approved these changes
LGTM

2023-03-27 15:33 UTC, kphalgun-px approved these changes
LGTM

2023-03-28 06:37 UTC, kphalgun-px commented on tests/backup/backup_resiliency_test.go
> +				err = DeleteRestore(restoreName, orgID, ctx)
@mkoppal-px suggested that there is no need to wait.

2023-03-28 12:07 UTC, lsrinivas-pure approved these changes
lgtm

2023-03-28 12:08 UTC, merged