[PDS]: Setup backup targets w.r.t supported Object stores.
portworx/torpedo pull request #1262
Opened 2023-03-28 08:28 UTC by gauraa2

This is the first backup PR, as part of this PR following packages and tests are added.
- pdsbackup package
      - This package comprises of pds backup utilities , which include various functions to create/delete backup creds/targets.
      - Also this comprises of helper functions for creating/deleting cloud object storage(includes AWS, GCP, Azure and S3 compatible)
 
-  Added backup test to setup backup targets w.r.t all the supported Object stores.

Logs: http://aetos.pwx.purestorage.com/resultSet/testSetID/143150

2023-03-30 09:50 UTC, Madanagopal19 commented
Attach jenkins logs and add description about this testcase

2023-03-30 10:05 UTC, Madanagopal19 requested changes
Minor comment

2023-03-30 10:05 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +	It("add all supported Object stores as backup target for data services", func() {
nit: Add all supported Object stores as backup target for data services

2023-03-30 10:05 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +		Step("Create AWS S3 Backup target.", func() {
Add step log to aetos dash board

2023-03-30 10:05 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +		StartTorpedoTest("ValidateBackupTargetsOnSupportedObjectStores", "Validate backup targets for all supported object stores.", nil, 0)
add pdsLabels

2023-03-30 10:05 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +	log.Info("Delete all the backup targets.")
use log.InfoD

2023-03-30 13:12 UTC, gauraa2 commented on tests/pds/backup_test.go
> +		Step("Create AWS S3 Backup target.", func() {
Done

2023-03-30 13:12 UTC, gauraa2 commented on tests/pds/backup_test.go
> +		StartTorpedoTest("ValidateBackupTargetsOnSupportedObjectStores", "Validate backup targets for all supported object stores.", nil, 0)
Done

2023-03-30 13:12 UTC, gauraa2 commented on tests/pds/backup_test.go
> +	log.Info("Delete all the backup targets.")
Done

2023-04-03 03:50 UTC, Madanagopal19 requested changes

2023-04-03 03:50 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +			bkpTarget, err := bkpClient.CreateGcpBackupCredsAndTarget(tenantID, fmt.Sprintf("%v-gcp", bkpTargetName))
how are we validating the backup target is created successfully or not ?
say if its api call we need to we need to assert its response, is that assertion part handled?

2023-04-03 03:50 UTC, Madanagopal19 commented on tests/pds/backup_test.go
> +		deleteAllBkpTargets()
similarly for delete backup targets, we need to validate if all the backup targets are deleted successfully.

2023-04-04 14:45 UTC, closed without merging