Deregister Target Cluster from PDS Control Plane
portworx/torpedo pull request #1277
Opened 2023-03-29 09:35 UTC by Madanagopal19

1. Deploy Data service
2. Delete Data service
3. Delete CRDs
4. Uninstall PDS helm chart
5. Validate the Deployment Target health status
6. Register back the Target Cluster

reference doc - https://pds.docs.portworx.com/admin-guide/remove-cluster/remove-cluster-wipe-data/

2023-03-30 09:15 UTC, gauraa2 requested changes

2023-03-30 09:17 UTC, Madanagopal19 commented on drivers/pds/lib/utils.go
> +	apiExtentions                           = apiextensions.Instance()
done

2023-03-31 09:41 UTC, gauraa2 approved these changes
LGTM

2023-04-03 10:34 UTC, aravindranath14 approved these changes
LGTM

2023-04-04 07:06 UTC, merged