Resiliency Test "RestartPXDuringAppScaleUp"
portworx/torpedo pull request #1327
Opened 2023-04-16 04:21 UTC by Madanagopal19

This PR has has the test RestartPXDuringAppScaleUp

2023-04-17 05:03 UTC, gauraa2 requested changes

2023-04-17 05:29 UTC, Madanagopal19 commented on tests/pds/pds_basic_test.go
> +		InitInstance()
Its a good catch, we have init instance as part of resiliency test framework. I will Utilize that.

2023-04-17 11:57 UTC, gauraa2 approved these changes

2023-04-17 11:58 UTC, aravindranath14 approved these changes
LGTM

2023-04-18 04:27 UTC, dbhatnagar-px approved these changes

2023-04-18 04:29 UTC, merged