Restart pds application pod during resource update
portworx/torpedo pull request #1330
Opened 2023-04-17 17:29 UTC by gauraa2

This PR has the test RestartAppDuringResourceUpdate

Deploy data service
Update the resource config, while upgrade is happening delete few pods.
Validate post deletion all the pods come up successfully.

2023-04-18 07:46 UTC, Madanagopal19 requested changes

2023-04-18 07:46 UTC, Madanagopal19 commented on tests/pds/resiliency_test.go
> +				if ds.Name != postgresql {
remove this check, we need to run the test for all data services

2023-04-18 07:46 UTC, Madanagopal19 commented on tests/pds/resiliency_test.go
> +					isDeploymentsDeleted = false
this flag is not required

2023-04-18 07:46 UTC, Madanagopal19 commented on tests/pds/resiliency_test.go
> +})
Add aftereach block and end torpedo test also close the resiliency channel

2023-04-18 07:46 UTC, Madanagopal19 commented on drivers/pds/lib/utils.go
> +	log.Infof("Deployment details.")
combine both the loggers

2023-04-18 07:46 UTC, Madanagopal19 commented on drivers/pds/lib/resiliency_utils.go
> +			UpdateDeploymentResourceConfig(deployment, "medium")
take template name as a constant

2023-04-18 07:46 UTC, Madanagopal19 commented on drivers/pds/lib/utils.go
> +		log.Infof("template - %v", template.GetName())
use log.Debugf incase if you are printing the names for debugging purpose

2023-04-18 11:46 UTC, dbhatnagar-px requested changes

2023-04-18 11:46 UTC, dbhatnagar-px commented on drivers/pds/lib/utils.go
> +		return err
Add this error in CapturedErrors Channel

2023-04-18 11:46 UTC, dbhatnagar-px commented on drivers/pds/lib/resiliency_utils.go
> +		CapturedErrors <- testError
Return testError as well

2023-04-18 11:53 UTC, dbhatnagar-px requested changes

2023-04-18 11:53 UTC, dbhatnagar-px commented on drivers/pds/lib/utils.go
> +	ResiliencyCondition <- true
ResiliencyCondition should be set only after validating that Update has started for atleast 1 pod

2023-04-18 17:08 UTC, Madanagopal19 requested changes

2023-04-18 17:08 UTC, Madanagopal19 commented on tests/pds/resiliency_test.go
> +					isDeploymentsDeleted = false
This is not addressed

2023-04-18 17:08 UTC, Madanagopal19 commented
Add test execution logs in description

2023-04-19 06:06 UTC, dbhatnagar-px approved these changes
Lgtm

2023-04-19 08:40 UTC, Madanagopal19 approved these changes
lgtm

2023-04-19 08:50 UTC, aravindranath14 approved these changes
Looks Good

2023-04-19 10:07 UTC, merged