method to update sticky flag in portworx volume driver
portworx/torpedo pull request #1367
Opened 2023-05-04 22:20 UTC by Rohit-PX

**What this PR does / why we need it**:
Portworx volume driver does not have a method to update sticky flag on portworx volumes

**Which issue(s) this PR fixes** (optional)
Closes # https://portworx.atlassian.net/browse/[PTX-17077](url)

**Special notes for your reviewer**:

2023-05-06 05:56 UTC, lsrinivas-pure requested changes

2023-05-06 05:56 UTC, lsrinivas-pure commented on drivers/volume/portworx/portworx.go
> +	nodes := node.GetWorkerNodes()
Please use getstoragedrivernodes, as in some cases like IKS there are worker nodes deployed for torpedo, with px disabled.

2023-05-15 19:38 UTC, nikolaypopov approved these changes
LGTM

2023-05-16 04:50 UTC, jainsmit approved these changes
LGTM !!

2023-05-16 05:00 UTC, lsrinivas-pure approved these changes
LGTM

2023-05-16 06:58 UTC, merged

2023-05-16 06:58 UTC, javedlingasur-px commented
As per the request, I have merged the fork with the main branch.