Handled error after updating the statefulset for ScaleMongoDBWhileBackupAndRestore  testcase: PA-1159
portworx/torpedo pull request #1418
Opened 2023-05-25 09:53 UTC by snigdha-px

**What this PR does / why we need it**:
Error was not handled after updating the statefulset
**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PA-1159

**Special notes for your reviewer**:

2023-05-25 10:00 UTC, kphalgun-px approved these changes
LGTM

2023-05-25 10:03 UTC, kshithijiyer-px requested changes

2023-05-25 10:03 UTC, kshithijiyer-px commented on tests/backup/backup_resiliency_test.go
> +			log.FailOnError(err, fmt.Sprintf("Scaling down MongoDB statefulset replica to 0"))
Can we use dash.verfiryfatel?

2023-05-25 10:04 UTC, kshithijiyer-px commented on tests/backup/backup_resiliency_test.go
>  			statefulSet, err = apps.Instance().GetStatefulSet(mongodbStatefulset, pxBackupNS)
Can we split this into multiple lines?

2023-05-25 10:08 UTC, snigdha-px commented on tests/backup/backup_resiliency_test.go
> +			log.FailOnError(err, fmt.Sprintf("Scaling down MongoDB statefulset replica to 0"))
done

2023-05-25 10:09 UTC, snigdha-px commented on tests/backup/backup_resiliency_test.go
>  			statefulSet, err = apps.Instance().GetStatefulSet(mongodbStatefulset, pxBackupNS)
As discussed, handling the error

2023-05-25 12:15 UTC, lsrinivas-pure approved these changes
LGTM

2023-05-26 02:29 UTC, merged

2023-05-26 04:52 UTC, snigdha-px commented
> Can you please add a link to a successful run?

https://jenkins.pwx.dev.purestorage.com/job/Users/job/Sumit/job/Custom-Pipelines/job/px-backup-on-demand-system-test-byoc/1443/consoleFull