PA-1322: check to stop execution if cluster is not in Healthy state
portworx/torpedo pull request #1512
Opened 2023-07-05 08:50 UTC by jkagliwal-px

This change to handle the testcase execution in case - 
When the target cluster is not in "HEALTHY" state, skip running tests and exit. 

Jenkins Run - Coming Soon

2023-07-10 09:56 UTC, dbhatnagar-px requested changes

2023-07-10 09:56 UTC, dbhatnagar-px commented on drivers/pds/targetcluster/targetcluster.go
> +		return "Target Cluster is not in healthy state, hence exiting the testcase execution", fmt.Errorf("error occured is: %v", err)
@jkagliwal-px the return should be in the form of nil,<error> and not <string>,<error>. Also you can embed the error message in returned error itself.

2023-07-12 05:19 UTC, Madanagopal19 approved these changes
LGTM

2023-07-12 09:02 UTC, aravindranath14 approved these changes
LGTM

2023-07-13 05:38 UTC, dbhatnagar-px approved these changes
Lgtm

2023-07-13 10:24 UTC, merged