Temporary solution for PA-1601
portworx/torpedo pull request #1639
Opened 2023-09-01 08:41 UTC by snigdha-px

**What this PR does / why we need it**:
Namespaces remain in Terminating state which cause next testcases to fail
**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:
This is a temp solution because the namespace seem to be in Terminating state forever with reason

 ```
NamespaceDeletionDiscoveryFailure            False   Thu, 31 Aug 2023 17:00:22 +0000  ResourcesDiscovered   All resources successfully discovered
  NamespaceDeletionGroupVersionParsingFailure  False   Thu, 31 Aug 2023 17:00:22 +0000  ParsedGroupVersions   All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Thu, 31 Aug 2023 17:00:22 +0000  ContentDeleted        All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    True    Thu, 31 Aug 2023 17:00:22 +0000  SomeResourcesRemain   Some resources are remaining: resourceexports.kdmp.portworx.com has 3 resource instances
  NamespaceFinalizersRemaining                 True    Thu, 31 Aug 2023 17:00:22 +0000  SomeFinalizersRemain  Some content in the namespace has finalizers remaining: kdmp.portworx.com/finalizer-cleanup in 3 resource instances
```

Method DeleteAppNamespace in backup_helper.go will also not solve this issue.
Need to find way to delete the finalizers

2023-09-01 13:12 UTC, mkoppal-px requested changes
Please do the following as mentioned here - https://github.com/portworx/torpedo/blob/master/tests/backup/backup_test.go#L300-L310

2023-09-22 14:15 UTC, kphalgun-px commented on tests/backup/backup_rancher_test.go
I am not sure if this is applicable to the changes that have been made, but `CloneAppContextAndTransformWithMappings` does not seem to actually perform a deep copy of the scheduler context; instead, it modifies the namespace field in the context based on the provided namespace mapping. This means, If the function is first used to modify the namespaces to represent restored namespaces, the original app context will subsequently contain these modified namespaces. A subsequent call to `CloneAppContextAndTransformWithMappings` would then need to use these modified, restored namespaces as keys in the namespace mapping, rather than the original ones.

For Example:

1. Original App Context Namespace: original-namespace
2. After first call to `CloneAppContextAndTransformWithMappings`, the namespace is changed to restored-namespace.
3. If calling `CloneAppContextAndTransformWithMappings` again, the namespace mapping should now have restored-namespace as the key to account for the changes made during the first call.

2023-09-26 05:32 UTC, snigdha-px commented on tests/backup/backup_rancher_test.go
Since this code is no more used, marking it as resolved

2023-09-26 06:07 UTC, kphalgun-px approved these changes
LGTM

2023-09-28 09:19 UTC, mkoppal-px approved these changes
LGTM

2023-09-28 10:32 UTC, merged