license test for IBM
portworx/torpedo pull request #1648
Opened 2023-09-06 13:52 UTC by Balachandar-Pan

**What this PR does / why we need it**:
license test for IBM
**Which issue(s) this PR fixes** (optional)
Closes #PTX-18543

**Special notes for your reviewer**:
https://jenkins.pwx.dev.purestorage.com/job/Torpedo/job/tp-nextpx-iks-catalog-pl/165/

2023-09-11 09:09 UTC, lsrinivas-pure requested changes

2023-09-11 09:09 UTC, lsrinivas-pure commented on tests/basic/license_test.go
> +						Expect(feature.Quantity).To(Equal(ibmLicense[Label(feature.Name)]),
use dash.verifyFatal here

2023-09-11 09:09 UTC, lsrinivas-pure commented on tests/basic/license_test.go
> +		ValidateApplications(contexts)
do u need to deploy apps for this valdiation?

2023-09-11 09:09 UTC, lsrinivas-pure commented on tests/basic/license_test.go
> +						Expect(feature.Quantity).To(Equal(ibmLicense[Label(feature.Name)]),
is this comparison correct quantity to ibmLicense[Label(feature.Name)]?

2023-09-25 10:23 UTC, closed without merging

2023-09-25 10:23 UTC, Balachandar-Pan commented
adding code to different branch