PA-1615: Adding IAMroles libraries and AutomationTests
portworx/torpedo pull request #1737
Opened 2023-10-09 10:23 UTC by jkagliwal-px

Initial Commit for Service Identity feature automation.

Added supporting libraries and added the Auth-token context switch feature.
Added the first testcase as well, which performs the below steps -

Create Service Identity with PDS Admin User
IAM roles - for service id a. namespace-admin - ns1 b. namespace-reader - ns2
Deploy TLS Enabled PG on ns1 with service identity token
Validate the Deployment
Run Workloads
Take Backup
Restore to ns2 -> expect failure
Update IAM for ns2 with admin role
Restore again on ns2 -> restore shuould be successful
Scale up restored dep on ns2
Clear all created entities.

Bug reported - https://portworx.atlassian.net/browse/DS-6679
Aetos Link - https://aetos.pwx.purestorage.com/resultSet/testSetID/360375
Jenkins Log - https://jenkins.pwx.dev.purestorage.com/job/PDS/job/pds-branch-build-test/540/console

2023-10-10 08:49 UTC, Madanagopal19 requested changes

2023-10-10 08:49 UTC, Madanagopal19 commented on tests/pds/pds_ds_rbac_test.go
> +						//pdsRestoreNsName, _, err = restoreClient.GetNameSpaceNameToRestore(backupJob.GetId(), pdsRestoreTargetClusterID, ns2.Name, false)
remove commented line

2023-10-12 12:22 UTC, Madanagopal19 approved these changes
LGTM

2023-10-13 05:08 UTC, aravindranath14 approved these changes
LGTM

2023-10-13 08:57 UTC, merged