Revert "PTX-22246 Fix atupilot tests validation issues (#2067)"
portworx/torpedo pull request #2075
Opened 2024-02-12 16:51 UTC by kshithijiyer-px

This reverts commit b2e0eae88c836f4d36e70f65d50e01564f8f0d43.

**What this PR does / why we need it**:
- [x] Revert "PTX-22246 Fix atupilot tests validation issues (#2067)" as it's causing pipeline failures in the nonpx run with the below trace: 
```
14:07:54    [PANICKED] in [JustAfterEach] - /usr/local/go/src/runtime/panic.go:261 @ 02/11/24 08:37:54.07
14:07:54    << Timeline
14:07:54  
14:07:54    [FAILED] Unexpected error:
14:07:54        <*errors.errorString | 0xc000e9cf40>: 
14:07:54        failed to get [autopilot] namespace, Err: the server could not find the requested resource (get storageclusters.core.libopenstorage.org)
14:07:54        {
14:07:54            s: "failed to get [autopilot] namespace, Err: the server could not find the requested resource (get storageclusters.core.libopenstorage.org)",
14:07:54        }
14:07:54    occurred
14:07:54    In [It] at: /go/src/github.com/portworx/torpedo/pkg/log/log.go:334 @ 02/11/24 08:37:32.068
14:07:54  
14:07:54    Full Stack Trace
14:07:54      github.com/portworx/torpedo/pkg/log.FailOnError({0x8a77720, 0xc000e9cf40}, {0x80a0dcc?, 0xc002037000?}, {0x0?, 0x6 
```

**Which issue(s) this PR fixes** (optional)
Closes #PB-5626

**Special notes for your reviewer**:

2024-02-12 16:53 UTC, mkoppal-px approved these changes
LGTM

2024-02-12 20:09 UTC, nikolaypopov requested changes
Please see this PR https://github.com/portworx/torpedo/pull/2076, this should fix the issue, also if you need a private image with this fix you can use `nikolaypopov/torpedo:PTX-22333`

2024-02-13 04:53 UTC, kshithijiyer-px commented
> Please see this PR #2076, this should fix the issue, also if you need a private image with this fix you can use `nikolaypopov/torpedo:PTX-22333`

I have tested your fix and commented on the mentioned PR will need to do additional change make sure it check if there is a pxNamespace and then check if autopilot is installed or not. If there is no PX it shouldn't check for autopliot

2024-02-13 05:32 UTC, nikolaypopov approved these changes

2024-02-13 05:32 UTC, merged