PTX-22333 Fix autopilot validation for backup tests
portworx/torpedo pull request #2076
Opened 2024-02-12 20:07 UTC by nikolaypopov

Fix autopilot validation for backup tests by not looking for PX and just getting list of all deployment and finding autopilot deployment and returning its namespace.

2024-02-12 21:18 UTC, Santhoshairody approved these changes

2024-02-13 04:51 UTC, kshithijiyer-px requested changes
We need to change to check to see 2 things, If px is there then only check if autopilot is there. So your check will become:

len(autopilotNamespace) == 0 && len(pxNamespace) != 0

2024-02-13 04:51 UTC, kshithijiyer-px commented on drivers/scheduler/k8s/k8s.go
> +	if len(autopilotNamespace) == 0 {
I tired running this what I am seeing is that the job is failing here. This check needs to be changed to check if PX as well as autopilot is there if not then only fails. This check currently fails if autopilot is not there even when there is no PX. 

The job which we are running here doesn't install both and hence it's causing it to fail. 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/Kshithij/job/kiyer-iks-patch-version/18/console

2024-03-19 04:10 UTC, nikolaypopov commented
Not needed anymore, fix was done in another PR

2024-03-19 04:10 UTC, closed without merging