provisioner volume snapshotclass mapping mapping
portworx/torpedo pull request #2151
Opened 2024-03-05 09:55 UTC by sn-px

**What this PR does / why we need it**:
Adding common function for passing provisioner volumesnapshotclass mapping

**Which issue(s) this PR fixes** (optional)
Closes #https://portworx.atlassian.net/browse/PB-5533

**Special notes for your reviewer**:

2024-03-05 13:01 UTC, mkoppal-px requested changes
Please create a separate function instead of modifying the existing one

2024-03-10 08:15 UTC, sn-px commented
> Please create a separate function instead of modifying the existing one

done

2024-03-18 09:48 UTC, lsrinivas-pure commented on tests/backup/backup_sanity_test.go
> +		backupNames          []string
Please remove this before merge

2024-03-18 09:48 UTC, lsrinivas-pure approved these changes
LGTM

2024-03-20 06:45 UTC, mkoppal-px requested changes
As discussed, please pass the volume snapshot map in the backup Request itself and keep the function signature of `AdditionalBackupRequestParams` unchanged

2024-03-20 11:00 UTC, sn-px commented
> As discussed, please pass the volume snapshot map in the backup Request itself and keep the function signature of `AdditionalBackupRequestParams` unchanged

-> Done

2024-03-21 03:29 UTC, mkoppal-px approved these changes
LGTM

2024-03-21 05:23 UTC, merged