Refactor API and GRPC to use inputs directly instead of WorkflowRequest
portworx/torpedo pull request #2203
Opened 2024-03-15 06:35 UTC by atrivedi-px

**What this PR does / why we need it**:
Refactor API and GRPC to use inputs directly instead of WorkflowRequest

**Which issue(s) this PR fixes** (optional)
Closes #DS-8589

**Special notes for your reviewer**:

2024-03-15 06:54 UTC, aravindranath14 approved these changes
LGTM

2024-03-15 10:05 UTC, Madanagopal19 requested changes

2024-03-15 10:16 UTC, atrivedi-px commented on tests/unifiedPlatform/platform/platform_test.go
> +				automationModels.UserName:        "testAccount1",
Done

2024-03-15 12:30 UTC, jkagliwal-px approved these changes

2024-03-18 04:03 UTC, Madanagopal19 approved these changes
lgtm

2024-03-18 04:54 UTC, merged