DS-8916: Refactoring Templates as per new PDS client
portworx/torpedo pull request #2325
Opened 2024-04-08 12:41 UTC by jkagliwal-px

solves - https://purestorage.atlassian.net/browse/DS-8916

Torpedo Build -

2024-04-09 15:51 UTC, Madanagopal19 requested changes

2024-04-09 15:54 UTC, Madanagopal19 requested changes

2024-04-09 15:54 UTC, Madanagopal19 commented on drivers/unifiedPlatform/pdsLibs/templateDefinitionLib.go
> +	log.InfoD("Temp value fromed in lib folder is- [%v]", templateValue)
nit: formed

2024-04-10 07:04 UTC, atrivedi-px approved these changes
LGTM

2024-04-10 07:17 UTC, aravindranath14 approved these changes

2024-04-10 08:32 UTC, merged

2024-04-10 08:34 UTC, Madanagopal19 approved these changes
Minor comment, approving the PR, kindly fix it before merging

2024-04-10 08:34 UTC, Madanagopal19 commented on drivers/unifiedPlatform/platform/backend/v1/api/templates.go
> +	err = utilities.CopyStruct(templateModel, &templateResponse.Create)
handle the error