Adding EnableandDisableNamespace
portworx/torpedo pull request #2463
Opened 2024-05-06 10:15 UTC by atrivedi-px

**What this PR does / why we need it**:
Adding EnableandDisableNamespace test

**Which issue(s) this PR fixes** (optional)
Closes #DS-7994

**Special notes for your reviewer**:

2024-05-06 10:22 UTC, aravindranath14 approved these changes
LGTM

2024-05-06 10:35 UTC, Madanagopal19 requested changes

2024-05-06 10:35 UTC, Madanagopal19 commented on tests/unifiedPlatform/pds2/pds_namespace_test.go
> +					if i%2 == 0 {
here i will be always `numberOfNamespacesTobeCreated`

2024-05-07 06:43 UTC, Madanagopal19 approved these changes
LGTM, kindly attach the jenkins logs before merging

2024-05-07 07:57 UTC, merged