[PTX-25143]ResizePoolDrivesInDifferentSize testcase fix
portworx/torpedo pull request #2690
Opened 2024-07-18 07:53 UTC by sayalasomayajula-px

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #
https://purestorage.atlassian.net/browse/PTX-25143

**Special notes for your reviewer**:
PASS LOGS: https://jenkins.pwx.dev.purestorage.com/job/Autopilot/job/tp-aut-nextpx-pks-pvc-and-pool-expand/684/display/redirect

2024-07-22 05:25 UTC, vumesh-px requested changes

2024-07-22 05:25 UTC, vumesh-px commented on tests/basic/storage_pool_test.go
> +		StartTorpedoTest("NodeAddDriveWhileAddDiskInProgress", "Initiate pool expansion using add-drive while one already in progress", nil, testrailID)
```suggestion
		StartTorpedoTest("NodeAddDiskWhileAddDiskInProgress", "Initiate pool expansion using add-drive while one already in progress", nil, testrailID)
```

2024-07-22 10:21 UTC, lsrinivas-pure approved these changes
LGTM

2024-07-22 10:21 UTC, lsrinivas-pure commented on tests/basic/storage_pool_test.go
> +	err = Inst().V.AddCloudDrive(&node, newSpec, poolID)
i think this is repeated, please check

2024-07-23 15:28 UTC, kphalgun-px commented on tests/basic/pool_function_test.go
> +		StartTorpedoTest("PoolExpandDiskResizePXRestart",
👍

2024-07-23 15:30 UTC, kphalgun-px commented on tests/basic/storage_pool_test.go
> +		response, _ := addDiskToSpecificPool(*nodeDetails, diskSize, poolID)
What about the error that addDiskToSpecificPool returns?

2024-07-23 15:33 UTC, kphalgun-px commented on tests/basic/storage_pool_test.go
> +		poolUUID := pickPoolToResize(contexts, api.SdkStoragePool_RESIZE_TYPE_ADD_DISK, diskSize)
We might need a check if poolUUID is empty.

2024-07-23 15:37 UTC, kphalgun-px commented on tests/basic/storage_pool_test.go
> +				paramsArr = append(paramsArr, fmt.Sprintf("size=%d", specSize))
```suggestion
				for _, pool := range poolDetails {
					if pool.ID == poolID {
						poolSize := pool.TotalSize / units.GiB
						paramsArr = append(paramsArr, fmt.Sprintf("size=%d", poolSize))
					}
				}
```

?

2024-08-01 11:29 UTC, vumesh-px approved these changes

2024-08-01 14:00 UTC, merged