:sprinkles: adding cloudsnap test for longevity
portworx/torpedo pull request #637
Opened 2021-10-18 04:56 UTC by lsrinivas-pure

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** (optional)
Closes #

**Special notes for your reviewer**:

2022-01-17 09:37 UTC, vinayakshnd commented
@lsrinivas-pure pls paste sucessful jenkins job run with these changes

2022-01-18 14:33 UTC, lsrinivas-pure commented
> 

Here is the result
http://jen-endurance.pwx.dev.purestorage.com/job/long-fa-sample-test/2/console

2022-01-19 08:14 UTC, Rohit-PX commented on tests/testTriggers.go
> +					logrus.Infof("snapshotScheduleName : %v", snapshotScheduleName)
```suggestion
					logrus.Infof("snapshotScheduleName : %v for volume: %s", snapshotScheduleName, v.name)
```

2022-01-19 08:19 UTC, Rohit-PX commented on tests/testTriggers.go
> +					UpdateOutcome(event, err)
This will also cause even `nil` errors to be added to outcome.
Can move `UpdateOutcome(event, err)` to after line 786 inside the `else` part

2022-01-19 08:23 UTC, Rohit-PX commented
Also run the tp-dev job once to make sure there are no regressions.

2022-01-19 08:23 UTC, Rohit-PX requested changes
Looks ok after running `tp-dev` job

2022-01-19 09:02 UTC, Rohit-PX approved these changes
LGTM after running the tp-dev job to check for regressions.

2022-01-19 11:51 UTC, lsrinivas-pure commented
> 

Ran the test and it is passing
https://jenkins.portworx.dev/job/Torpedo/job/tp-dev-test/973/console

2022-01-19 11:52 UTC, merged