Add wrapper functions for pds apis and utilities
portworx/torpedo pull request #863
Opened 2022-09-06 10:26 UTC by gauraa2

This PR add the wrapper functions w.r.t pds apis and utilities, which can be further utilized for PDS system test automation.

2022-09-07 06:59 UTC, lsrinivas-pure requested changes

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/api/account.go
> +// GetAccountsList func
elobrate what it returns

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/api/dataServiceDeployment.go
> +		// ApplicationConfigurationOverrides:  &appConfigOverride,
delete if not required

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/controlplane/controlplane.go
> +		log.Panicf("Unable to fetch the tenant info.\n Error - %v", err)
return the error and handle it in calling function, any clean up activity if trquired will not happen if panic is used

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/pdsutils/environment.go
> +// Environment lhasha
give proper comment

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/targetcluster/targetcluster.go
> +		log.Panic(err)
once panic next statement will not be executed

2022-09-07 06:59 UTC, lsrinivas-pure commented on drivers/pds/targetcluster/targetcluster.go
> +		return "Connection Refused!!", err
will it be always connection refused?

2022-09-19 10:36 UTC, lsrinivas-pure commented
Hi @gauraa2 

Plz create an image and run this job for regression 
[Torpedo-Dev](https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev01/)

2022-09-20 06:34 UTC, gauraa2 commented
Hi @lsrinivas-pure 
Please find below the jobs for creating the image and running the regression :
 - Build the image: https://jenkins.pwx.dev.purestorage.com/job/DevOps/job/build-torpedo/186/
 - Torpedo regression: https://jenkins.pwx.dev.purestorage.com/job/Dev/job/torpedo-dev01/175/console

2022-09-20 06:45 UTC, lsrinivas-pure approved these changes
LGTM

2022-09-20 06:47 UTC, merged