PTX-14602 Upgrade StorageCluster test and methods
portworx/torpedo pull request #988
Opened 2022-12-19 21:16 UTC by nikolaypopov

Upgrade StorageCluster test and methods

Signed-off-by: nikolaypopov <nikolay.popov86@gmail.com>

2022-12-20 19:10 UTC, nikolaypopov commented
Job is running here https://jenkins.pwx.dev.purestorage.com/job/Torpedo/view/Torpedo%20Upgrade/job/tp-upgrade-stc/2/console

2022-12-20 23:52 UTC, CharudathGopal approved these changes

2022-12-21 02:22 UTC, nikolaypopov commented
Never mind I need to rewrite the logic and improve it a bit more, got some ideas from talking to @mborodin-px, will need some time

2022-12-21 07:14 UTC, lsrinivas-pure approved these changes
LGTM

2022-12-22 18:14 UTC, nikolaypopov commented
Had a successful run for both StorageCluster and Daemonset with Stork upgrade by default

2023-01-11 19:50 UTC, mborodin-px commented on drivers/volume/linstor/linstor.go
> +
nit: remove this empty line

2023-01-11 19:50 UTC, mborodin-px commented on drivers/volume/portworx/portworx.go
> +		return fmt.Errorf("failed to create local local snapshot using PXCTL, Err: %v", err)
double `local` words

2023-01-11 20:54 UTC, mborodin-px requested changes
test Request changes

2023-01-11 21:09 UTC, nikolaypopov commented on drivers/volume/portworx/portworx.go
> +		return fmt.Errorf("failed to create local local snapshot using PXCTL, Err: %v", err)
Done

2023-01-11 21:09 UTC, nikolaypopov commented on drivers/volume/linstor/linstor.go
> +
Done

2023-01-13 00:19 UTC, mborodin-px approved these changes
LGTM

2023-01-13 00:21 UTC, nikolaypopov commented
We have validated `operator` and `generic` upgrades here https://jenkins.pwx.dev.purestorage.com/job/Users/job/Maksym/job/tp-upgrade-pipeline04/105/console
I also ran multiple of my nextpx jobs with same image, no issues were found, will keep an eye on this after I merge

2023-01-13 00:23 UTC, merged